<footer class="block block-bg-light">
  <div>
    <ul>
      <li><a href="/guide">Guide</a></li>
      <li><a href="/api">API</a></li>
      <li><a href="/plugins">Plugins</a></li>
      <li><a href="/release">Release</a></li>
    </ul>
    <div class="license">Released under the MIT License <a href="https://github.com/eggjs"><img src="https://zos.alipayobjects.com/rmsportal/kAZMouoCzSoaDbD.svg"/></a></div>
  </div>
</footer>
