<header class="block block-bg-dark">
  <div class="nav">
    <h1 class="nav-logo">
      <a href="/"><img src="https://zos.alipayobjects.com/rmsportal/NhoSIAympGgsRee.svg"></a>
    </h1>
    <ul>
      {{ menu_link() }}
      <li>
        <iframe src="https://ghbtns.com/github-btn.html?user=eggjs&repo=egg&type=star&count=false" frameborder="0" scrolling="0" width="54px" height="20px"></iframe>
      </li>
    </ul>
  </div>
</header>
