
  <div class="block block-bg-dark banner center">
    <div class="banner-logo">egg logo</div>
    <h2 class="ft-b">A web framework's framework for Node.js</h2>
    <p class="ft-m">build by alibaba group.</p>
    <div class="banner-button">
      <a class="btn btn-primary" href="/guide/">Get Started</a>
    </div>
  </div>

  <div class="block version center">
    <div>
      <span>Latest: <a>1.2.1</a></span>
      <span>Stable: <a>1.1.0</a></span>
      <span>Nodejs >  <a>4.x</a></span>
    </div>
  </div>

  <div class="block info block-bg-light center">
    <h2 class="ft-b">Ｗe build the framework's framework  </h2>
    <h3 class="ft-m">Ｗe build the framework's framework  </h3>
    <ul>
      <li>
        <div class="info-img">
          <img src="https://zos.alipayobjects.com/rmsportal/PRxOrrjBrTcACnE.svg" />
        </div>
        <h4>cluster management</h4>
        <div>aaa</div>
      </li>
      <li>
        <div class="info-img">
          <img src="https://zos.alipayobjects.com/rmsportal/aYQsKTxvyZLtnVS.svg" />
        </div>
        <h4>Plugin System</h4>
        <div>aaa</div>
      </li>
      <li>
        <div class="info-img">
          <img src="https://zos.alipayobjects.com/rmsportal/GAldlsiewJjYaBp.svg" />
        </div>
        <h4>customimation</h4>
        <div>aaa</div>
      </li>
    </ul>
  </div>

  <div class="block guide center">
    <h2 class="ft-b">Get Started</h2>
    <p class="ft-m">Ｗe build the framework's framework  </p>
    <p class="guide-code">code</p>
    <p class="ft-m ft-w">Need Help</p>
    <p>Ｗe build the framework's framework  </p>
  </div>
